# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capistrano-php}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Felder, Namics"]
  s.date = %q{2009-10-18}
  s.description = %q{Use capistrano for PHP deployment without overriding all methods by yourself.}
  s.email = %q{christian.felder@namics.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "capistrano-php.gemspec",
     "lib/capistrano/php.rb",
     "lib/init.rb",
     "pkg/capistrano-php-0.1.0.gem",
     "pkg/capistrano-php-0.1.0.tar.gz",
     "pkg/capistrano-php-0.1.0/Manifest",
     "pkg/capistrano-php-0.1.0/README.rdoc",
     "pkg/capistrano-php-0.1.0/Rakefile",
     "pkg/capistrano-php-0.1.0/capistrano-php.gemspec",
     "pkg/capistrano-php-0.1.0/lib/capistrano/php.rb",
     "pkg/capistrano-php-0.1.0/lib/init.rb"
  ]
  s.homepage = %q{http://github.com/namics/capistrano-php}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Use capistrano for PHP deployment without overriding all methods by yourself.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
